### ISSUE TITLE
標準添付ライブラリがrequireできない

### ISSUE THREAD

**Issue by suruseas** [suruseas/docs-ruby-lang-support#2]
- そもそもruby.wasm単体だとrequire自体ができない？
- 標準添付ライブラリがruby.wasmに含まれていない？

**Comment by suruseas** [comment]
ruby.wasmをbuildし直せば良さそう？

https://github.com/ruby/ruby.wasm#profiles

**Comment by suruseas** [comment]
https://github.com/ruby/ruby.wasm/blob/394841d142fabc2287e7f918a605c7009e545846/packages/npm-packages/ruby-head-wasm-wasi/package.json#L19

>     "build:wasm": "../ruby-wasm-wasi/tools/pack-ruby-wasm.sh ../../../rubies/head-wasm32-unknown-wasi-full-js-debug ./dist",

これだったらfullぽいんだけどな。。

**Comment by suruseas** [comment]
以下だとrequireできる。

```html
<html lang="ja">
<head>
  <title>RubyWasm</title>
  <meta charset="utf-8" />
</head>
<script src="https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@latest/dist/browser.script.iife.js"></script>
<script type="text/ruby" charset="UTF-8">
  eval(<<~CODE)
    require "date"
    puts Date.new(1993, 2, 24)
  CODE
  </script>
</html>
```

**Comment by suruseas** [comment]
以下だとrequireできない。

[参照元](https://github.com/ruby/ruby.wasm/tree/main/packages/npm-packages/ruby-3_2-wasm-wasi#quick-start-for-browser)

```html
<html>
  <script src="https://cdn.jsdelivr.net/npm/@ruby/wasm-wasi@latest/dist/browser.umd.js"></script>
  <script>
    const { DefaultRubyVM } = window["ruby-wasm-wasi"];
    const main = async () => {
      // Fetch and instantiate WebAssembly binary
      const response = await fetch(
        //      Tips: Replace the binary with debug info if you want symbolicated stack trace.
        //      (only nightly release for now)
        //      "https://cdn.jsdelivr.net/npm/ruby-3_2-wasm-wasi@next/dist/ruby.debug+stdlib.wasm"
        "https://cdn.jsdelivr.net/npm/ruby-3_2-wasm-wasi@latest/dist/ruby.wasm"
      );
      const buffer = await response.arrayBuffer();
      const module = await WebAssembly.compile(buffer);
      const { vm } = await DefaultRubyVM(module);

      vm.printVersion();
      vm.eval(`
        require "js"
        luckiness = ["Lucky", "Unlucky"].sample
        JS::eval("document.body.innerText = '#{luckiness}'")
      `);
    };

    main();
  </script>
  <body></body>
</html>
```

**Comment by suruseas** [comment]
おおお、👆のコメントに書いてあった！下記でrequireできた。

```js
      const response = await fetch(
        //      Tips: Replace the binary with debug info if you want symbolicated stack trace.
        //      (only nightly release for now)
        //      "https://cdn.jsdelivr.net/npm/ruby-3_2-wasm-wasi@next/dist/ruby.debug+stdlib.wasm"
        "https://cdn.jsdelivr.net/npm/ruby-3_2-wasm-wasi@latest/dist/ruby+stdlib.wasm"
      );
```

確認したところ

- ruby.wasm
  - 14.21 MB
- ruby.stdlib.wasm
  - 30.83 MB

なので、サイズの問題そう。

**Comment by suruseas** [comment]
原因判明。npmパッケージでインストールしたバージョンが古すぎた😭

v2.0.0にはdist内に ruby+stdlib.wasm が存在していたのでそちらを使うように修正する

**Comment by suruseas** [comment]
解決と思ったが、v2.0.0だと以下のCSPのエラーが出てしまう。

```
Error: /usr/local/lib/ruby/site_ruby/3.2.0/js.rb:38:in `eval': EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*".
 (JS::Error)
/usr/local/lib/ruby/site_ruby/3.2.0/js.rb:38:in `<module:JS>'
/usr/local/lib/ruby/site_ruby/3.2.0/js.rb:37:in `<top (required)>'
eval:2:in `require'
eval:2:in `<main>'
```
これは、0.4.0以降に入った下記のJS.evalで起こっていた

https://github.com/ruby/ruby.wasm/commit/e4468e041d38eb0907e9eece3d07c642ce026581

```ruby
module JS
  Undefined = JS.eval("return undefined")
  Null = JS.eval("return null")
end
```

JS.evalしているためchromeの機能拡張の仕様で動作できないようで、sandboxなどを利用すると大丈夫なようである。
以下参考

- https://qiita.com/Freedom645/items/74dbff34c3ffd8d3a9fd
- https://scrapbox.io/pokutuna/Chrome_Extension_%E3%81%A7%E3%83%A6%E3%83%BC%E3%82%B6%E5%85%A5%E5%8A%9B%E3%82%92_eval_%E3%81%99%E3%82%8B

**Comment by suruseas** [comment]
調べてみた。

- JS.evalはこの機能拡張では使用しないので使わない機能が阻害要因となっている
- sandboxに移動する案はたしかに動作するだろうが、sandbox側でロードされたruby環境からはcontext側domは直接触れなくなるので現状よりも機能が制限される。

以上を踏まえると、選択肢は下記２つかも…

- 0.3.0を自前でbuildして、ruby+stdlib.wasm をbuildする
  - 多分デフォルトではbuildできないと思うので、buildスクリプトの修正が必要かも
- 2.0.0のソースでJS.evalを無効化して手元でbuildする

結局どちらにせよ手元でwasmのrebuildは必要なのでその線で進める。

**Comment by suruseas** [comment]
wasmのrebuildには失敗したが、対応策を見つけたので一旦wasmのrebuildのメモだけ残しておく。

※以下は失敗する

```
# 環境が整っているのでwasi-sdkをベースにする
FROM --platform linux/amd64 ghcr.io/webassembly/wasi-sdk
RUN apt-get update && \
    apt-get install -y make git rake curl
#1
RUN cd /root/ruby.wasm/build/toolchain/wasi-sdk/
RUN rm -rf wasi-sdk
RUN tar -zxvf wasi-sdk.tar.gz
RUN mv wasi-sdk-14.0 wasi-sdk
RUN rake build:head-wasm32-unknown-wasi-full-js
```
